repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: flake8
    - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      #  language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    - id: isort
