sudo: false
language: generic
env:
  global:
    - PKG_NAME="kmtools"
    - DB_CONNECTION_STRING="mysql://root:@127.0.0.1:3306"
install:
  - wget --no-verbose -O anaconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda config --append channels bioconda
  - conda config --append channels omnia
  - conda config --append channels kimlab
  - conda config --append channels ostrokach
  - conda info -a
  - conda update -q conda
  - conda install -q --yes conda-build anaconda-client git-lfs
  - git lfs pull
  - conda build devtools/conda-recipe/
script:
  - conda create -n _test $PKG_NAME --use-local
  - source activate _test
  - conda install pypy
  - pip install -q flake8 pytest pytest-runner pytest-cov pytest-logging hypothesis
  - flake8
  - py.test
  - source deactivate
after_success:
  - echo "Success!"
  - pip install codecov
  - codecov
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      devtools/travis-ci/build-docs.sh
      anaconda -t $ANACONDA_TOKEN upload /home/travis/anaconda/conda-bld/linux-64/*.tar.bz2;
    fi
after_failure:
  - echo "Failure!"
after_script:
  - echo "X_X"
