{% set name = "kmtools" %}
{% set version = "0.0.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - pycurl
    - retrying
    - paramiko
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - scikit-learn
    - pytables
    - numba
    - biopython
    - kmbio
    # Plotting
    # - matplotlib
    # - seaborn
    # IPython
    # - ipython
    # - pygments
    # Binaries
    - blast
    - muscle
    - cifparse-obj  # Assemblies

test:
  imports:
    - kmtools
    - kmtools.db_tools
    - kmtools.df_tools
    - kmtools.py_tools
    - kmtools.sequence_tools
    - kmtools.structure_tools
    - kmtools.system_tools

about:
  home: http://kimlaborg.github.io/kmtools
  license: MIT
  summary: Helpful bioinformatics scripts.
