{% set name = "kmtools" %}
{% set version = "0.0.17.dev0" %}

package:
  name: {{ version }}
  version: {{ version }}

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - retrying
    - paramiko
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - scikit-learn
    - pytables
    - numba
    - kmbio
    # Required by lxml
    - icu
    - libiconv
    # Plotting
    # - matplotlib
    # - seaborn
    # IPython
    # - ipython
    # - pygments
    # Binaries
    - blast
    - muscle
    - cifparse-obj  # Assemblies

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - pytest-logging
    - pypy
    - flake8
  imports:
    - kmtools

about:
  home: http://kimlaborg.github.io/kmtools
  license: MIT
  summary: Helpful bioinformatics scripts.
