{% set version = "0.0.1" %}

package:
  name: ascommon
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
      # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - retrying
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - retrying

test:
  imports:
    - ascommon

about:
  home: kimlab.org
  license: MIT
  summary: Helpful bioinformatics scripts.

