{% set version = "0.0.2" %}

package:
  name: ascommon
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - pytables
    - biopython
    - retrying

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
  imports:
    - ascommon

about:
  home: http://ostrokach.github.io/ascommon
  license: MIT
  summary: Helpful bioinformatics scripts.
