{% set version = "0.0.4" %}

package:
  name: ascommon
  version: {{ version }}

source:
  path: ../../

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - six
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - scikit-learn
    - matplotlib
    - pytables
    - numba
    - biopython
    # IPython
    - ipython
    - pygments

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
  imports:
    - ascommon

about:
  home: http://ostrokach.github.io/ascommon
  license: MIT
  summary: Helpful bioinformatics scripts.
