{% set version = "0.0.7" %}

package:
  name: kmtools
  version: {{ version }}

source:
  path: ../../

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - six
    - retrying
    - paramiko
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - scikit-learn
    - pytables
    - numba
    - biopython
    # Plotting
    - matplotlib
    - seaborn
    # IPython
    - ipython
    - pygments
    # Binaries
    - blast

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - pypy
  imports:
    - kmtools

about:
  home: http://pmklab.github.io/kmtools
  license: MIT
  summary: Helpful bioinformatics scripts.
