 {% set version = "0.0.15" %}

package:
  name: kmtools
  version: {{ version }}

source:
  path: ../../

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    # Basic python
    - python
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - lxml
    - pycurl
    - retrying
    - paramiko
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - scikit-learn
    - pytables
    - numba
    - biopython
    # Required by lxml
    - icu
    - libiconv
    # Plotting
    # - matplotlib
    # - seaborn
    # IPython
    # - ipython
    # - pygments
    # Binaries
    - blast
    - muscle

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - pytest-logging
    - pypy
    - flake8
  imports:
    - kmtools

about:
  home: http://kimlaborg.github.io/kmtools
  license: MIT
  summary: Helpful bioinformatics scripts.
