{% set name = "kmtools" %}
{% set version = "0.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - SUBPKG_NAME

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
  run:
    # Basic python
    - python
    - ruamel.yaml
    - requests
    - retrying
    - paramiko
    - cloudpickle
    - psutil
    - pygments
    - pytest
    # Scientific python
    - numpy
    - scipy
    - pandas
    - sqlalchemy
    - pyarrow
    - mdtraj
    - pdf2svg
    - reduce
    # Kimlab
    - kmbio >=2.0.21

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-benchmark
    - hypothesis
  imports:
    - kmtools
    - kmtools.db_tools
    - kmtools.df_tools
    - kmtools.py_tools
    - kmtools.sequence_tools
    - kmtools.structure_tools
    - kmtools.system_tools

# outputs:
#   - name: {{ name }}
#     type: conda
#   - type: wheel
#     requirements:
#       - cython

about:
  home: http://kimlaborg.github.io/kmtools
  license: MIT
  summary: Helpful bioinformatics scripts.
